COPY A.rec C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.rec 00a01_RES.txt
COPY A.svd C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.svd 00b02_SVA.txt
COPY A.pst C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.pst 00c03_PST.txt
COPY A.cnd C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.cnd 00d04_CNA.txt
COPY A.par C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.par 00e05_PAR.txt
COPY A.sen C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.sen 00f06_SEN.txt
COPY A.seo C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.seo 00g07_SEO.txt
COPY A.res C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.res 00h08_RES.txt
COPY A.bpa C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.bpa 00h09_BPA.txt

COPY A.sin C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.sin 00i09_SIN.txt 
COPY A.bpa C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.bpa 00k10_BPA____BPA2.par
COPY A.bpa C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.bpa 09_BPA____.csv

COPY A.rec C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.rec 01_REC____.csv
COPY A.svd C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.svd 02_SVD______.csv
COPY A.pst C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.pst 03_PST____.csv
COPY A.cnd C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.cnd 04_CND____.csv
COPY A.par C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.par 05_PAR______.csv
COPY A.sen C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.sen 06_SEN______.csv
COPY A.seo C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.seo 07_SEO______.csv
COPY A.res C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.res 08_RES____.csv
COPY A.sin C:\pest\A\Cataclima
RENAME C:\pest\A\Cataclima\A.sin 09_SIN______.csv	
